name: Tests

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  tests:

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        framework: [net6.0, net8.0, net9.0, net462]
        exclude:
          - os: macos-latest
            framework: net462
          - os: ubuntu-latest
            framework: net462
        include:
          - sln: src/GitContext.sln
          - os: windows-latest
            sln: src\GitContext.sln

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore ${{ matrix.sln }}
    - name: Build with dotnet
      run: dotnet build ${{ matrix.sln }} --configuration Release --no-restore
    - name: Run unit tests
      run: dotnet test ${{ matrix.sln }} --configuration Release --no-build --verbosity normal -f ${{ matrix.framework }}
